version: '3'
services:
    client-app:
        build:
            context: ./web
        ports:
            - '3000:80'

    file-explorer:
        image: filebrowser/filebrowser
        container_name: file-explorer
        ports:
            - '4000:80'
        volumes:
            - ./data:/srv
        restart: always

    college-api:
        build:
            context: ./services
        ports:
            - '5005:80'
        volumes:
            - ./uploads:/app/uploads

    nginx:
        build:
            context: ./tools/nginx
        ports:
            - '80:80'
        depends_on:
            - client-app
            - college-api
