version: '3'
services:
    client-app:
        build:
            context: ./web
        ports:
            - '3000:80'

    college-api:
        build:
            context: ./services
        ports:
            - '5001:5001'
        volumes:
            - /Users/mac/Desktop/storage:/root/storage
    cat:
        build:
            context: ./tools/CAT
        ports:
            - '4000:80'

    nginx:
        build:
            context: ./tools/nginx
        ports:
            - '80:80'
        depends_on:
            - client-app
            - college-api
