FROM mcr.microsoft.com/mssql/server:2019-latest

# We will overwrite these variables in the script  docker-server-magic.ps1
ENV SA_PASSWORD YourStrongPassword123
ENV ACCEPT_EULA=Y
ENV MSSQL_DB_NAME YourDatabaseName
ENV MSSQL_DB_USER YourDatabaseUser
ENV MSSQL_DB_PASSWORD YourDatabasePassword

EXPOSE 1433
