name: CI Build (services, web, CAT)

on:
  pull_request:
    branches: [ "development" ]

jobs:
  dotNet-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd ./services
        dotnet restore
    - name: Build .NET
      run: |
        cd ./services
        dotnet build --no-restore

  web-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'
    - name: Install dependencies
      run: |
        cd ./web
        npm install
    - name: Build React app
      run: |
        cd ./web
        npm run build

  cat-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd ./tools/CAT
        npm install

    - name: Build College Admin Panel
      run: |
        cd ./tools/CAT
        npm run build
